freeslot(
"MT_GUARDIANBODY",
"MT_GUARDIANHEAD",
"MT_GUARDLEFTHAND",
"MT_GUARDRIGHTHAND",
"S_GUARDIANBODY",
"S_GUARDIANHEAD_STND",
"S_GUARDIANHEAD_1543",
"S_GUARDIANHEAD_1544",
"S_GUARDIANHEAD_1545",
"S_GUARDIANHEAD_1546",
"S_GUARDATKDECISION_1547",
"S_GUARDATKDECISION_1548",
"S_GUARDATKDECISION_1549",
"S_GUARDATKDECISION_1550",
"S_GUARDATKDECISION_1551",
"S_GUARDATKDECISION_1552",
"S_GUARDATKDECISION_1553",
"S_GUARDATKDECISION_1554",
"S_GUARDATKDECISION_1555",
"S_GUARDATKDECISION_1556",
"S_GUARDATKDECISION_1557",
"S_GUARDATKDECISION_1558",
"S_GUARDATKDECISION_1559",
"S_GUARDATKDECISION_1560",
"S_GUARDATKDECISION_1561",
"S_GUARDATKDECISION_1562",
"S_GUARDATKDECISION_1563",
"S_GUARDATKDECISION_1564",
"S_GUARDATKDECISION_1980",
"S_GUARDATKDECISION_1981",
"S_GUARDIANPAIN_1565",
"S_GUARDIANPAIN_1566",
"S_GUARDIANPAIN_1567",
"S_GUARDIANPAIN_1568",
"S_GUARDIANPAIN_1569",
"S_GUARDIANDEATH_1571",
"S_GUARDIANDEATH_1572",
"S_GUARDIANDEATH_1573",
"S_GUARDIANXDEATH_1574",
"S_GUARDIANDEATH_1575",
"S_GUARDIANDEATH_1576",
"S_GUARDLEFTHAND_STND",
"S_GUARDLHANDATK_1576",
"S_GUARDLHANDATK_1638",
"S_GUARDLHANDATK_1639",
"S_GUARDLHANDATK_1640",
"S_GUARDLHANDATK_1641",
"S_GUARDLHANDATK_1642",
"S_GUARDLHANDATK_1643",
"S_GUARDLHANDPAIN_1644",
"S_GUARDLHANDPAIN_1645",
"S_GUARDLHANDDEATH_1646",
"S_GUARDLHANDDEATH_1647",
"S_GUARDLHANDDEATH_1648",
"S_GUARDLHANDXDEATH_1649",
"S_GUARDRIGHTHAND_STND",
"S_GUARDRHANDATK_1612",
"S_GUARDRHANDATK_1613",
"S_GUARDRHANDATK_1614",
"S_GUARDRHANDATK_1615",
"S_GUARDRHANDATK_1616",
"S_GUARDRHANDATK_1617",
"S_GUARDRHANDATK_1618",
"S_GUARDRHANDPAIN_1619",
"S_GUARDRHANDPAIN_1620",
"S_GUARDRHANDDEATH_1621",
"S_GUARDRHANDDEATH_1622",
"S_GUARDRHANDDEATH_1623",
"S_GUARDRHANDXDEATH_1624"
)

--GuardianBody

mobjinfo[MT_GUARDIANBODY] = {
    --$Category Metal Guardian Boss
    --$Name Guardian Body
    --$Sprite F033B0
    doomednum = 211,
    spawnstate = S_GUARDIANBODY,
    spawnhealth = 1000,
    seestate = 0,
    seesound = 0,
    reactiontime = 8,
    attacksound = 0,
    painstate = 0,
    painchance = 0,
    painsound = 0,
    meleestate = 0,
    missilestate = 0,
    deathstate = 0,
    deathsound = 0,
    xdeathstate = 0,
    speed = 0,
    radius = 2621440,
    height = 2621440,
    mass = 100,
    damage = 0,
    activesound = 0,
    raisestate = 0,
    flags = MF_SOLID|MF_SCENERY
}

states[S_GUARDIANBODY] = {SPR_EMW5_METALGUARDIAN, B, -1, nil, 0, 0, S_NULL}

--MetalGuardianHead

mobjinfo[MT_GUARDIANHEAD] = {
    --$Category Metal Guardian Boss
    --$Name Guardian Head
    --$Sprite F033A0
    doomednum = 212,
    spawnstate = S_GUARDIANHEAD_STND,
    spawnhealth = 10,
    seestate = S_GUARDIANHEAD_1543,
    seesound = 0,
    reactiontime = 8,
    attacksound = sfx_zoom,
    painstate = S_GUARDIANPAIN_1565,
    painchance = MT_THOK,
    painsound = sfx_grdhrt,
    meleestate = S_GUARDATKDECISION_1547,
    missilestate = S_GUARDATKDECISION_1547,
    deathstate = S_GUARDIANDEATH_1571,
    deathsound = sfx_cybdth,
    xdeathstate = S_GUARDIANXDEATH_1574,
    speed = 0,
    radius = 1966080,
    height = 4621440,
    mass = 0,
    damage = 0,
    activesound = sfx_guard1,
    raisestate = 0,
    flags = MF_SPECIAL|MF_SHOOTABLE|MF_BOSS
}

--GuardianLook
states[S_GUARDIANHEAD_STND] = {SPR_EMW5_METALGUARDIAN, A, 1, A_Look, 0, 0, S_GUARDIANHEAD_STND}

--GuardianActive
states[S_GUARDIANHEAD_1543] = {SPR_EMW5_METALGUARDIAN, A, 3, A_PlaySound, sfx_guard1, 1, S_GUARDIANHEAD_1544}
states[S_GUARDIANHEAD_1544] = {SPR_EMW5_METALGUARDIAN, A, 3, A_Chase, 0, 0, S_GUARDIANHEAD_1545}
states[S_GUARDIANHEAD_1545] = {SPR_EMW5_METALGUARDIAN, A, 3, A_Chase, 0, 0, S_GUARDIANHEAD_1546}
states[S_GUARDIANHEAD_1546] = {SPR_EMW5_METALGUARDIAN, A, 3, A_Chase, 0, 0, S_GUARDIANHEAD_1544}

--GuardianAttackDecision
states[S_GUARDATKDECISION_1547] = {SPR_EMW5_METALGUARDIAN, A, 0, A_RandomState, S_GUARDATKDECISION_1548, S_GUARDATKDECISION_1549, S_GUARDATKDECISION_1548}

--1
states[S_GUARDATKDECISION_1548] = {SPR_EMW5_METALGUARDIAN, A, 0, A_RandomState, S_GUARDATKDECISION_1550, S_GUARDATKDECISION_1553, S_GUARDATKDECISION_1548}

--2
states[S_GUARDATKDECISION_1549] = {SPR_EMW5_METALGUARDIAN, A, 0, A_RandomState, S_GUARDATKDECISION_1557, S_GUARDATKDECISION_1562, S_GUARDATKDECISION_1549}

--1-1
states[S_GUARDATKDECISION_1550] = {SPR_EMW5_METALGUARDIAN, A, 2, A_FaceTarget, 0, 0, S_GUARDATKDECISION_1551}
states[S_GUARDATKDECISION_1551] = {SPR_EMW5_METALGUARDIAN, A, 70, A_TurretFire, MT_TURRETLASER, 0, S_GUARDATKDECISION_1552}
states[S_GUARDATKDECISION_1552] = {SPR_EMW5_METALGUARDIAN, A, 1, A_TurretStop, 0, 0, S_GUARDIANHEAD_1543}

--1-2
states[S_GUARDATKDECISION_1553] = {SPR_EMW5_METALGUARDIAN, A, 1, A_FaceTarget, 0, 0, S_GUARDATKDECISION_1554}
states[S_GUARDATKDECISION_1554] = {SPR_EMW5_METALGUARDIAN, A, 1, A_FireShot, MT_ROCKET, 5, S_GUARDATKDECISION_1555}
states[S_GUARDATKDECISION_1555] = {SPR_EMW5_METALGUARDIAN, A, 1, A_FireShot, MT_ROCKET, 35, S_GUARDATKDECISION_1556}
states[S_GUARDATKDECISION_1556] = {SPR_EMW5_METALGUARDIAN, A, 1, A_FireShot, MT_ROCKET, 70, S_GUARDIANHEAD_1543}

--2-1
states[S_GUARDATKDECISION_1557] = {SPR_EMW5_METALGUARDIAN, A, 1, A_FaceTarget, 0, 0, S_GUARDATKDECISION_1558}
states[S_GUARDATKDECISION_1558] = {SPR_EMW5_METALGUARDIAN, A, 100, A_PlaySound, sfx_guard2, 0, S_GUARDATKDECISION_1559}
states[S_GUARDATKDECISION_1559] = {SPR_EMW5_METALGUARDIAN, A, 1, A_MixUp, 0, 0, S_GUARDATKDECISION_1980}
states[S_GUARDATKDECISION_1980] = {SPR_EMW5_METALGUARDIAN, A, 70, A_LinedefExecute, 242, 0, S_GUARDATKDECISION_1981}
states[S_GUARDATKDECISION_1981] = {SPR_EMW5_METALGUARDIAN, A, 70, A_LinedefExecute, 243, 0, S_GUARDATKDECISION_1560}
states[S_GUARDATKDECISION_1560] = {SPR_EMW5_METALGUARDIAN, A, 1, A_FaceTarget, 0, 0, S_GUARDATKDECISION_1561}
states[S_GUARDATKDECISION_1561] = {SPR_EMW5_METALGUARDIAN, A, 5, A_FireShot, MT_ROCKET, 25, S_GUARDIANHEAD_1543}

--2-2
states[S_GUARDATKDECISION_1562] = {SPR_EMW5_METALGUARDIAN, A, 1, A_FaceTarget, 0, 0, S_GUARDATKDECISION_1563}
states[S_GUARDATKDECISION_1563] = {SPR_EMW5_METALGUARDIAN, A, 10, A_FaceTarget, 0, 0, S_GUARDATKDECISION_1564}
states[S_GUARDATKDECISION_1564] = {SPR_EMW5_METALGUARDIAN, A, 10, A_FireShot, MT_ROCKET, 15, S_GUARDIANHEAD_1543}

--pain
states[S_GUARDIANPAIN_1565] = {SPR_EMW5_METALGUARDIAN, A, 1, A_TurretStop, 0, 0, S_GUARDIANPAIN_1566}
states[S_GUARDIANPAIN_1566] = {SPR_EMW5_METALGUARDIAN, A, 28, A_PlaySound, sfx_grdhrt, 1, S_GUARDIANPAIN_1567}
states[S_GUARDIANPAIN_1567] = {SPR_EMW5_METALGUARDIAN, A, 70, A_SuperTurretFire, MT_SHOOPDAWHOOP, 0, S_GUARDIANPAIN_1568}
states[S_GUARDIANPAIN_1568] = {SPR_EMW5_METALGUARDIAN, A, 1, A_RandomState, S_GUARDIANPAIN_1567, S_GUARDIANPAIN_1569, S_GUARDIANPAIN_1568}
states[S_GUARDIANPAIN_1569] = {SPR_EMW5_METALGUARDIAN, A, 1, A_TurretStop, 0, 0, S_GUARDIANHEAD_STND}

--Death
states[S_GUARDIANDEATH_1571] = {SPR_EMW5_METALGUARDIAN, A, 4, A_Fall, 0, 0, S_GUARDIANDEATH_1572}
states[S_GUARDIANDEATH_1572] = {SPR_EMW5_METALGUARDIAN, A, 4, A_BossScream, 0, 0, S_GUARDIANDEATH_1575}
states[S_GUARDIANDEATH_1575] = {SPR_EMW5_METALGUARDIAN, A, 4, A_BossScream, 0, 0, S_GUARDIANDEATH_1576}
states[S_GUARDIANDEATH_1576] = {SPR_EMW5_METALGUARDIAN, A, 4, A_BossScream, 0, 0, S_GUARDIANDEATH_1573}
states[S_GUARDIANDEATH_1573] = {SPR_EMW5_METALGUARDIAN, A, -1, A_BossDeath, 0, 0, S_NULL}

states[S_GUARDIANXDEATH_1574] = {SPR_EMW5_METALGUARDIAN, A, 5, nil, 0, 0, S_GUARDIANXDEATH_1574}

--MetalGuardianLeftHand

mobjinfo[MT_GUARDLEFTHAND] = {
    --$Category Metal Guardian Boss
    --$Name Guardian Left Hand
    --$Sprite F033C0
    doomednum = 213,
    spawnstate = S_GUARDLEFTHAND_STND,
    spawnhealth = 5,
    seestate = S_GUARDLHANDATK_1576,
    seesound = 0,
    reactiontime = 8,
    attacksound = sfx_zoom,
    painstate = S_GUARDLHANDPAIN_1644,
    painchance = MT_THOK,
    painsound = sfx_grdhrt,
    meleestate = S_GUARDLHANDATK_1638,
    missilestate = S_GUARDLHANDATK_1638,
    deathstate = S_GUARDLHANDDEATH_1646,
    deathsound = sfx_cybdth,
    xdeathstate = S_GUARDLHANDXDEATH_1649,
    speed = 0,
    radius = 1966080,
    height = 4966080,
    mass = 0,
    damage = 0,
    activesound = 0,
    raisestate = 0,
    flags = MF_SPECIAL|MF_SHOOTABLE|MF_BOSS
}

--GuardianLHandLook
states[S_GUARDLEFTHAND_STND] = {SPR_EMW5_METALGUARDIAN, C, 1, A_Look, 0, 0, S_GUARDLEFTHAND_STND}

--GuardianLHandActive
states[S_GUARDLHANDATK_1576] = {SPR_EMW5_METALGUARDIAN, C, 3, A_Chase, 0, 0, S_GUARDLHANDATK_1576}

--GuardianLHandDecide
states[S_GUARDLHANDATK_1638] = {SPR_EMW5_METALGUARDIAN, C, 1, A_RandomState, S_GUARDLHANDATK_1639, S_GUARDLHANDATK_1641, S_GUARDLHANDATK_1638}

--GuardianLHandEnergyBomb
states[S_GUARDLHANDATK_1639] = {SPR_EMW5_METALGUARDIAN, E, 70, A_FaceTarget, 0, 0, S_GUARDLHANDATK_1640}
states[S_GUARDLHANDATK_1640] = {SPR_EMW5_METALGUARDIAN, E, 35, A_SuperFireShot, MT_JETTBULLET, 25, S_GUARDLEFTHAND_STND}

--GuardianLHandFlameThrower
states[S_GUARDLHANDATK_1641] = {SPR_EMW5_METALGUARDIAN, E, 70, A_FaceTarget, 0, 0, S_GUARDLHANDATK_1642}
states[S_GUARDLHANDATK_1642] = {SPR_EMW5_METALGUARDIAN, E, 65, A_TurretFire, MT_TURRETLASER, 0, S_GUARDLHANDATK_1643}
states[S_GUARDLHANDATK_1643] = {SPR_EMW5_METALGUARDIAN, E, 1, A_TurretStop, 0, 0, S_GUARDLEFTHAND_STND}

--GuardianLHandPain
states[S_GUARDLHANDPAIN_1644] = {SPR_EMW5_METALGUARDIAN, C, 1, A_TurretStop, 0, 0, S_GUARDLHANDPAIN_1645}
states[S_GUARDLHANDPAIN_1645] = {SPR_EMW5_METALGUARDIAN, C, 28, A_Pain, 0, 0, S_GUARDLEFTHAND_STND}

--GuardianLHandDeath
states[S_GUARDLHANDDEATH_1646] = {SPR_EMW5_METALGUARDIAN, C, 4, A_Fall, 0, 0, S_GUARDLHANDDEATH_1647}
states[S_GUARDLHANDDEATH_1647] = {SPR_EMW5_METALGUARDIAN, C, 4, A_BossScream, 0, 0, S_GUARDLHANDDEATH_1648}
states[S_GUARDLHANDDEATH_1648] = {SPR_EMW5_METALGUARDIAN, C, -1, A_BossDeath, 0, 0, S_NULL}

states[S_GUARDLHANDXDEATH_1649] = {SPR_EMW5_METALGUARDIAN, C, 5, nil, 0, 0, S_GUARDLHANDXDEATH_1649}

--MetalGuardianRightHand

mobjinfo[MT_GUARDRIGHTHAND] = {
    --$Category Metal Guardian Boss
    --$Name Guardian Right Hand
    --$Sprite F033D0
    doomednum = 214,
    spawnstate = S_GUARDRIGHTHAND_STND,
    spawnhealth = 5,
    seestate = S_GUARDRHANDATK_1612,
    seesound = 0,
    reactiontime = 8,
    attacksound = sfx_zoom,
    painstate = S_GUARDRHANDPAIN_1619,
    painchance = MT_THOK,
    painsound = sfx_grdhrt,
    meleestate = S_GUARDRHANDATK_1613,
    missilestate = S_GUARDRHANDATK_1613,
    deathstate = S_GUARDRHANDDEATH_1621,
    deathsound = sfx_cybdth,
    xdeathstate = S_GUARDRHANDXDEATH_1624,
    speed = 0,
    radius = 1966080,
    height = 4966080,
    mass = 0,
    damage = 0,
    activesound = 0,
    raisestate = 0,
    flags = MF_SPECIAL|MF_SHOOTABLE|MF_BOSS
}

--GuardianRHandLook
states[S_GUARDRIGHTHAND_STND] = {SPR_EMW5_METALGUARDIAN, D, 1, A_Look, 0, 0, S_GUARDRIGHTHAND_STND}

--GuardianRHandActive
states[S_GUARDRHANDATK_1612] = {SPR_EMW5_METALGUARDIAN, D, 3, A_Chase, 0, 0, S_GUARDRHANDATK_1612}

--GuardianRHandDecide
states[S_GUARDRHANDATK_1613] = {SPR_EMW5_METALGUARDIAN, D, 1, A_RandomState, S_GUARDRHANDATK_1614, S_GUARDRHANDATK_1616, S_GUARDRHANDATK_1613}

--GuardianRHandEnergyBomb
states[S_GUARDRHANDATK_1614] = {SPR_EMW5_METALGUARDIAN, F, 70, A_FaceTarget, 0, 0, S_GUARDRHANDATK_1615}
states[S_GUARDRHANDATK_1615] = {SPR_EMW5_METALGUARDIAN, F, 35, A_SuperFireShot, MT_JETTBULLET, 25, S_GUARDRIGHTHAND_STND}

--GuardianRHandFlameThrower
states[S_GUARDRHANDATK_1616] = {SPR_EMW5_METALGUARDIAN, F, 70, A_FaceTarget, 0, 0, S_GUARDRHANDATK_1617}
states[S_GUARDRHANDATK_1617] = {SPR_EMW5_METALGUARDIAN, F, 65, A_TurretFire, MT_TURRETLASER, 0, S_GUARDRHANDATK_1618}
states[S_GUARDRHANDATK_1618] = {SPR_EMW5_METALGUARDIAN, F, 1, A_TurretStop, 0, 0, S_GUARDRIGHTHAND_STND}

--GuardianRHandPain
states[S_GUARDRHANDPAIN_1619] = {SPR_EMW5_METALGUARDIAN, D, 1, A_TurretStop, 0, 0, S_GUARDRHANDPAIN_1620}
states[S_GUARDRHANDPAIN_1620] = {SPR_EMW5_METALGUARDIAN, D, 28, A_Pain, 0, 0, S_GUARDRIGHTHAND_STND}

--GuardianRHandDeath
states[S_GUARDRHANDDEATH_1621] = {SPR_EMW5_METALGUARDIAN, D, 4, A_Fall, 0, 0, S_GUARDRHANDDEATH_1622}
states[S_GUARDRHANDDEATH_1622] = {SPR_EMW5_METALGUARDIAN, D, 4, A_BossScream, 0, 0, S_GUARDRHANDDEATH_1623}
states[S_GUARDRHANDDEATH_1623] = {SPR_EMW5_METALGUARDIAN, D, -1, A_BossDeath, 0, 0, S_NULL}

states[S_GUARDRHANDXDEATH_1624] = {SPR_EMW5_METALGUARDIAN, D, 5, nil, 0, 0, S_GUARDRHANDXDEATH_1624}