sfxinfo[sfx_mtl01] = {true, 96, SF_TOTALLYSINGLE|SF_X4AWAYSOUND|SF_X8AWAYSOUND}
sfxinfo[sfx_mtl03] = {true, 96, SF_TOTALLYSINGLE|SF_X8AWAYSOUND}
sfxinfo[sfx_guard2] = {true, 127, SF_TOTALLYSINGLE|SF_X4AWAYSOUND|SF_X8AWAYSOUND}
sfxinfo[sfx_grdhrt] = {false, 96, SF_TOTALLYSINGLE|SF_X4AWAYSOUND|SF_X8AWAYSOUND}
sfxinfo[sfx_emxpld] = {true, 34, SF_X4AWAYSOUND|SF_X8AWAYSOUND}
sfxinfo[sfx_erghit] = {false, 127, SF_TOTALLYSINGLE|SF_X4AWAYSOUND|SF_X8AWAYSOUND}
sfxinfo[sfx_emw001] = {false, 120, SF_TOTALLYSINGLE|SF_X4AWAYSOUND|SF_X8AWAYSOUND}
sfxinfo[sfx_shdw01] = {false, 80, SF_X4AWAYSOUND|SF_X8AWAYSOUND}
-- FlyBySounds
sfxinfo[sfx_mtl04] = {false, 4, SF_X2AWAYSOUND|SF_X4AWAYSOUND|SF_X8AWAYSOUND|SF_OUTSIDESOUND}
sfxinfo[sfx_mtl05] = {false, 4, SF_X2AWAYSOUND|SF_X4AWAYSOUND|SF_X8AWAYSOUND|SF_OUTSIDESOUND}

-- MetalGuardianSounds
sfxinfo[sfx_guard1] = {false, 64, SF_X4AWAYSOUND|SF_X8AWAYSOUND}