SafeFreeslot("MT_EMWSHADOW_CHAOSBLAST",
		 "SPR_EMW5_CHAOSBLAST",
         "S_EMWSHADOW_CHAOSBLAST_1",
		 "S_EMWSHADOW_CHAOSBLAST_2",
		 "S_EMWSHADOW_CHAOSBLAST_3",
		 "S_EMWSHADOW_CHAOSBLAST_4",
		 "S_EMWSHADOW_CHAOSBLAST_5",
		 "S_EMWSHADOW_CHAOSBLAST_6",
		 "S_EMWSHADOW_CHAOSBLAST_7",
		 "S_EMWSHADOW_CHAOSBLAST_8",
		 "S_EMWSHADOW_CHAOSBLAST_9",
		 "S_EMWSHADOW_CHAOSBLAST_10",
		 "S_EMWSHADOW_CHAOSBLAST_11",
		 "S_EMWSHADOW_CHAOSBLAST_12",
		 "S_EMWSHADOW_CHAOSBLAST_13",
		 "MT_EMWSHADOW_CHAOSBLAST_DEBRIS1",
		 "MT_EMWSHADOW_CHAOSBLAST_DEBRIS2",
		 "MT_EMWSHADOW_CHAOSBLAST_DEBRIS3",
         "S_EMWSHADOW_CHAOSBLAST_DEBRIS1_1",
		 "S_EMWSHADOW_CHAOSBLAST_DEBRIS1_2",
		 "S_EMWSHADOW_CHAOSBLAST_DEBRIS2",
		 "S_EMWSHADOW_CHAOSBLAST_DEBRIS3",
		 "S_EMWSHADOW_CHAOSBLAST_DEBRISDEATH",
		 "sfx_chaos1"
)

sfxinfo[sfx_chaos1] = {false, 60, 0}

mobjinfo[MT_EMWSHADOW_CHAOSBLAST] = {
    doomednum = -1,
	seesound = sfx_chaos1,
	spawnstate = S_EMWSHADOW_CHAOSBLAST_1,
    spawnhealth = 1000,
	reactiontime = 8,
	mass = 16,
	radius = 2097152,
	height = 4194304,
	flags = MF_NOBLOCKMAP|MF_NOGRAVITY|MF_NOCLIP|MF_SCENERY
}

states[S_EMWSHADOW_CHAOSBLAST_1] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|A, 1, A_CapeChase, 144, nil, S_EMWSHADOW_CHAOSBLAST_2}
states[S_EMWSHADOW_CHAOSBLAST_2] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|A, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_3}
states[S_EMWSHADOW_CHAOSBLAST_3] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|A, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_4}
states[S_EMWSHADOW_CHAOSBLAST_4] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|A, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_5}
states[S_EMWSHADOW_CHAOSBLAST_5] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|E, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_6}
states[S_EMWSHADOW_CHAOSBLAST_6] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|F, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_7}
states[S_EMWSHADOW_CHAOSBLAST_7] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|A, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_8}
states[S_EMWSHADOW_CHAOSBLAST_8] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|B, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_9}
states[S_EMWSHADOW_CHAOSBLAST_9] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|C, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_10}
states[S_EMWSHADOW_CHAOSBLAST_10] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|D, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_11}
states[S_EMWSHADOW_CHAOSBLAST_11] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|D, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_12}
states[S_EMWSHADOW_CHAOSBLAST_12] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|D, 2, A_CapeChase, nil, nil, S_EMWSHADOW_CHAOSBLAST_13}
states[S_EMWSHADOW_CHAOSBLAST_13] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|D, 2, A_OldRingExplode, MT_EMWSHADOW_CHAOSBLAST_DEBRIS1, nil, S_NULL}

mobjinfo[MT_EMWSHADOW_CHAOSBLAST_DEBRIS1] = {
    doomednum = -1,
	spawnstate = S_EMWSHADOW_CHAOSBLAST_DEBRIS1_1,
	deathstate = S_EMWSHADOW_CHAOSBLAST_DEBRISDEATH,
	deathsound = sfx_rxplod,
    spawnhealth = 1000,
	reactiontime = 8,
	speed = 2110720,
	mass = 16,
	radius = 14097152,
	height = 15094304,
	damage = 20,
	flags = MF_NOBLOCKMAP|MF_NOGRAVITY|MF_MISSILE
}
mobjinfo[MT_EMWSHADOW_CHAOSBLAST_DEBRIS2] = {
    doomednum = -1,
	spawnstate = S_EMWSHADOW_CHAOSBLAST_DEBRIS1_2,
	deathstate = S_EMWSHADOW_CHAOSBLAST_DEBRISDEATH,
	deathsound = sfx_rxplod,
    spawnhealth = 1000,
	reactiontime = 8,
	speed = 2110720,
	mass = 16,
	radius = 14097152,
	height = 15094304,
	damage = 20,
	flags = MF_NOBLOCKMAP|MF_NOGRAVITY|MF_MISSILE
}
mobjinfo[MT_EMWSHADOW_CHAOSBLAST_DEBRIS3] = {
    doomednum = -1,
	spawnstate = S_EMWSHADOW_CHAOSBLAST_DEBRISDEATH,
	deathstate = S_EMWSHADOW_CHAOSBLAST_DEBRISDEATH,
	deathsound = sfx_rxplod,
    spawnhealth = 1000,
	reactiontime = 8,
	speed = 2110720,
	mass = 16,
	radius = 14097152,
	height = 15094304,
	damage = 20,
	flags = MF_NOBLOCKMAP|MF_NOGRAVITY|MF_MISSILE
}

states[S_EMWSHADOW_CHAOSBLAST_DEBRIS1_1] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|0, 4, A_OldRingExplode, MT_EMWSHADOW_CHAOSBLAST_DEBRIS1, 0, S_EMWSHADOW_CHAOSBLAST_DEBRIS2}
states[S_EMWSHADOW_CHAOSBLAST_DEBRIS1_2] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|0, 4, A_OldRingExplode, MT_EMWSHADOW_CHAOSBLAST_DEBRIS2, 0, S_EMWSHADOW_CHAOSBLAST_DEBRIS2}
states[S_EMWSHADOW_CHAOSBLAST_DEBRIS2] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|1, 4, nil, nil, nil, S_EMWSHADOW_CHAOSBLAST_DEBRIS3}
states[S_EMWSHADOW_CHAOSBLAST_DEBRIS3] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|1, 4, nil, nil, nil, S_EMWSHADOW_CHAOSBLAST_DEBRISDEATH}
states[S_EMWSHADOW_CHAOSBLAST_DEBRISDEATH] = {SPR_EMW5_CHAOSBLAST, FF_FULLBRIGHT|TR_TRANS80|1, 4, nil, nil, nil, S_NULL}